# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alert.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'alert.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lert.proto\x12\x1fnetwork_notifications.alerts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x05\n\x15\x41lertStreamingMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61lert_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x13\n\x0btenant_name\x18\x04 \x01(\t\x12\x13\n\x06msp_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08msp_name\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\t \x01(\t\x12\x10\n\x08severity\x18\n \x01(\t\x12(\n\x04time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\toperation\x18\x0c \x01(\t\x12\r\n\x05state\x18\r \x01(\t\x12\x14\n\x07site_id\x18\x0e \x01(\tH\x02\x88\x01\x01\x12\x14\n\x0c\x63onfig_scope\x18\x0f \x01(\t\x12\x0f\n\x07summary\x18\x10 \x01(\t\x12\x16\n\tsite_name\x18\x11 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05notes\x18\x12 \x01(\tH\x04\x88\x01\x01\x12L\n\x11impacted_entities\x18\x13 \x01(\x0b\x32\x31.network_notifications.alerts.v1.ImpactedEntities\x12M\n\x12\x61\x64\x64itional_details\x18\x14 \x03(\x0b\x32\x31.network_notifications.alerts.v1.AdditionalDetail\x12\x15\n\x08priority\x18\x15 \x01(\tH\x05\x88\x01\x01\x42\t\n\x07_msp_idB\x0b\n\t_msp_nameB\n\n\x08_site_idB\x0c\n\n_site_nameB\x08\n\x06_notesB\x0b\n\t_priority\"\x93\x01\n\x10\x41\x64\x64itionalDetail\x12O\n\x07\x65ntries\x18\x01 \x03(\x0b\x32>.network_notifications.alerts.v1.AdditionalDetail.EntriesEntry\x1a.\n\x0c\x45ntriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"=\n\x10ImpactedEntities\x12\x15\n\rdevice_serial\x18\x01 \x03(\t\x12\x12\n\nclient_mac\x18\x02 \x03(\tBH\n1com.hpe.greenlake.network_notifications.alerts.v1B\x13\x41lertStreamingProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alert_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1com.hpe.greenlake.network_notifications.alerts.v1B\023AlertStreamingProto'
  _globals['_ADDITIONALDETAIL_ENTRIESENTRY']._loaded_options = None
  _globals['_ADDITIONALDETAIL_ENTRIESENTRY']._serialized_options = b'8\001'
  _globals['_ALERTSTREAMINGMESSAGE']._serialized_start=82
  _globals['_ALERTSTREAMINGMESSAGE']._serialized_end=724
  _globals['_ADDITIONALDETAIL']._serialized_start=727
  _globals['_ADDITIONALDETAIL']._serialized_end=874
  _globals['_ADDITIONALDETAIL_ENTRIESENTRY']._serialized_start=828
  _globals['_ADDITIONALDETAIL_ENTRIESENTRY']._serialized_end=874
  _globals['_IMPACTEDENTITIES']._serialized_start=876
  _globals['_IMPACTEDENTITIES']._serialized_end=937
# @@protoc_insertion_point(module_scope)
